# @format

on: [push]

jobs:
  test_one_env:
    runs-on: ubuntu-latest
    name: test_node_env
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16.x'
      - name: test_github_classroom
        run: |
          echo "console.log(process.env)" > index.js
          node index.js
